@baseUrl=http://localhost:3000

###

# @name login

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "bruna@email.com",
  "password": "123456"
}

###

GET {{baseUrl}}/users/me
Authorization: Bearer {{login.response.body.token}}